### ISSUE TITLE
`post delete` command triggers fatal error with PHP 8.0

### ISSUE THREAD

**Issue by gerasimovdaniel** [humanmade/orphan-command#9]
**How to replicate:**
Run `wp orphan post delete` on php 8.x.
On my installation it causes `PHP Fatal error:  Uncaught TypeError: HumanMade\OrphanCommand\Orphan_Post_Command::delete_orphan(): Return value must be of type bool, WP_Post returned in /srv/.wp-cli/packages/vendor/humanmade/orphan-command/inc/Orphan_Post_Command.php:141`

**I guess the issue is here:**
```
File: /inc/Orphan_Post_Command.php

/**
* Delete the orphan post with the given ID.
*
* @param int $id Orphan ID.
*
* @return bool Whether or not the orphan post has been deleted successfully.
*/
protected function delete_orphan( int $id ): bool {

    return wp_delete_post( $id, true );
}
```
The `delete_orphan` method is expected to return a boolean value, but the `wp_delete_post` function within it returns a `WP_Post` object on success and `false` or `null` only on failure. https://developer.wordpress.org/reference/functions/wp_delete_post/#return

**Comment by bootstrapthemes** [comment]
We confirm this error.
The following workaround was required in `Orphan_Post_Command.php:141`:

```php
protected function delete_orphan( int $id ): bool {
  if ( wp_delete_post( $id, true ) ) { return true; }
  else { return false; }
}
```
